import { Inn } from '../types/inn';
import { InnType } from '../types/inntype';
import { INNTYPES } from '../mockdata/mockinntypes';
import { Ciudad } from '../types/ciudad';
import { CIUDADES } from '../mockdata/mockcities';

export const INNS: Inn[] = [
    {
        id: 1,
        name: 'FLAMENGO/LARGO DO MACHADO - ÓTIMA LOCALIZAÇÃO',
        city: CIUDADES.find( (el) => el.slug === 'rio-de-janeiro'),
        imgs: [
            'https://a0.muscache.com/im/pictures/cb8c9a36-25c7-49ea-9f8f-17a072a5646d.jpg?aki_policy=xx_large',
            'https://a0.muscache.com/im/pictures/8b8ff3f4-1634-45bc-ad3f-45f8c535794c.jpg?aki_policy=large',
            'https://a0.muscache.com/im/pictures/9dfac763-65cd-4653-b0b8-154b686fcd42.jpg?aki_policy=large',
            'https://a0.muscache.com/im/pictures/6be116d6-bbb1-4eb5-881e-a24f674fe6df.jpg?aki_policy=large'
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
    {
        id: 2,
        name: 'Habitación en el corazón de Copacabana',
        city: CIUDADES.find( (el) => el.slug === 'rio-de-janeiro'),
        imgs: [
            'https://a0.muscache.com/im/pictures/81792668/c2e845a7_original.jpg?aki_policy=xx_large',
            'https://a0.muscache.com/im/pictures/81792717/1ec8c187_original.jpg?aki_policy=large',
            'https://a0.muscache.com/im/pictures/81792807/a0761ea4_original.jpg?aki_policy=large',
            'https://a0.muscache.com/im/pictures/55913196/0044264f_original.jpg?aki_policy=large'
        ],
        rating: 4.6,
        ratingQty: 15,
        price: 12,
        rooms: 1,
        bathrooms: 1,
        capacity: 2,
        innType: INNTYPES[1],
    },
    {
        id: 3,
        name: 'The penthouse terrace, a paradise in Copacabana',
        city: CIUDADES.find( (el) => el.slug === 'rio-de-janeiro'),
        imgs: [
            'https://a0.muscache.com/im/pictures/37741252/52db969a_original.jpg?aki_policy=xx_large',
            'https://a0.muscache.com/im/pictures/78333891/bbe9cb59_original.jpg?aki_policy=large',
            'https://a0.muscache.com/im/pictures/44491468/4d5f07e5_original.jpg?aki_policy=large',
            'https://a0.muscache.com/im/pictures/36752533/c9dffe47_original.jpg?aki_policy=large'
        ],
        rating: 4.9,
        ratingQty: 235,
        price: 125,
        rooms: 1,
        bathrooms: 1,
        capacity: 2,
        innType: INNTYPES[3],
    },
    {
        id: 4,
        name: 'Estudio entre Ipanema/Copacabana',
        city: CIUDADES.find( (el) => el.slug === 'rio-de-janeiro'),
        imgs: [
            'https://a0.muscache.com/im/pictures/41279903/50026858_original.jpg?aki_policy=xx_large',
            'https://a0.muscache.com/im/pictures/41279945/d00ee3fd_original.jpg?aki_policy=large',
            'https://a0.muscache.com/im/pictures/41280349/e0f0aa27_original.jpg?aki_policy=large',
            'https://a0.muscache.com/im/pictures/41280434/5b04d2d4_original.jpg?aki_policy=large'
        ],
        rating: 3.9,
        ratingQty: 101,
        price: 24,
        rooms: 3,
        bathrooms: 1,
        capacity: 9,
        innType: INNTYPES[4],
    },
    {
        id: 5,
        name: 'Boemia carioca',
        city: CIUDADES.find( (el) => el.slug === 'rio-de-janeiro'),
        imgs: [
            'https://a0.muscache.com/im/pictures/2f19e19e-447b-4f86-93dc-98d0d95a18fc.jpg?aki_policy=xx_large',
            'https://a0.muscache.com/im/pictures/1904ddfa-2f1d-47d5-bbc0-5397e601c5d5.jpg?aki_policy=large',
            'https://a0.muscache.com/im/pictures/afecd1fe-0a15-4f10-b4ba-5b3dab5dc4f6.jpg?aki_policy=large',
            'https://a0.muscache.com/im/pictures/3f91f881-3a2a-4198-8bcc-1b4286cc9c2e.jpg?aki_policy=large'
        ],
        rating: 4.8,
        ratingQty: 17,
        price: 78,
        rooms: 4,
        bathrooms: 2,
        capacity: 12,
        innType: INNTYPES[5],
    },
    {
        id: 1,
        name: 'Casa bonita',
        city: CIUDADES.find( (el) => el.slug === 'sao-paulo'),
        imgs: [
            '',
            '',
            '',
            ''
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
    {
        id: 1,
        name: 'Casa bonita',
        city: CIUDADES.find( (el) => el.slug === 'sao-paulo'),
        imgs: [
            '',
            '',
            '',
            ''
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
    {
        id: 1,
        name: 'Casa bonita',
        city: CIUDADES.find( (el) => el.slug === 'sao-paulo'),
        imgs: [
            '',
            '',
            '',
            ''
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
    {
        id: 1,
        name: 'Casa bonita',
        city: CIUDADES.find( (el) => el.slug === 'sao-paulo'),
        imgs: [
            '',
            '',
            '',
            ''
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
    {
        id: 1,
        name: 'Casa bonita',
        city: CIUDADES.find( (el) => el.slug === 'sao-paulo'),
        imgs: [
            '',
            '',
            '',
            ''
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
    {
        id: 1,
        name: 'Casa bonita',
        city: CIUDADES.find( (el) => el.slug === 'sao-paulo'),
        imgs: [
            '',
            '',
            '',
            ''
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
    {
        id: 1,
        name: 'Casa bonita',
        city: CIUDADES.find( (el) => el.slug === 'sao-paulo'),
        imgs: [
            '',
            '',
            '',
            ''
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
    {
        id: 1,
        name: 'Casa bonita',
        city: CIUDADES.find( (el) => el.slug === 'sao-paulo'),
        imgs: [
            '',
            '',
            '',
            ''
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
    {
        id: 1,
        name: 'Casa bonita',
        city: CIUDADES.find( (el) => el.slug === 'sao-paulo'),
        imgs: [
            '',
            '',
            '',
            ''
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
    {
        id: 1,
        name: 'Casa bonita',
        city: CIUDADES.find( (el) => el.slug === 'sao-paulo'),
        imgs: [
            '',
            '',
            '',
            ''
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
    {
        id: 1,
        name: 'Casa bonita',
        city: CIUDADES.find( (el) => el.slug === 'florianopolis'),
        imgs: [
            '',
            '',
            '',
            ''
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
    {
        id: 1,
        name: 'Casa bonita',
        city: CIUDADES.find( (el) => el.slug === 'florianopolis'),
        imgs: [
            '',
            '',
            '',
            ''
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
    {
        id: 1,
        name: 'Casa bonita',
        city: CIUDADES.find( (el) => el.slug === 'florianopolis'),
        imgs: [
            '',
            '',
            '',
            ''
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
    {
        id: 1,
        name: 'Casa bonita',
        city: CIUDADES.find( (el) => el.slug === 'florianopolis'),
        imgs: [
            '',
            '',
            '',
            ''
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
    {
        id: 1,
        name: 'Casa bonita',
        city: CIUDADES.find( (el) => el.slug === 'florianopolis'),
        imgs: [
            '',
            '',
            '',
            ''
        ],
        rating: 4.4,
        ratingQty: 135,
        price: 99,
        rooms: 2,
        bathrooms: 1,
        capacity: 3,
        innType: INNTYPES[0],
    },
];
